package com.yes.tfgapp.domain.fixed

enum class FixedProducts(
    val id: Int = 0,
    val productName: String,
    val categoryId: Int
) {
    /*Manzana(productName="Manzana", categoryId= FixedCategories.COMIDA.id),
    Pera( productName="Pera",categoryId= FixedCategories.COMIDA.id),
    Pan( productName="Pan", categoryId= FixedCategories.BEBIDAS.id),
    Leche( productName="Leche", categoryId= FixedCategories.BEBIDAS.id),
    Detergente( productName="Detergente", categoryId= FixedCategories.LIMPIEZA.id),
    Lavavajillas( productName="Lavavajillas", categoryId= FixedCategories.LIMPIEZA.id),*/

    //Frutas-Verduras
    Manzanas(productName="Manzanas", categoryId=FixedCategories.FYV.id),
    Platanos(productName="Plátanos", categoryId=FixedCategories.FYV.id),
    Naranjas(productName="Naranjas", categoryId=FixedCategories.FYV.id),
    Fresas(productName="Fresas", categoryId=FixedCategories.FYV.id),
    Uvas(productName="Uvas", categoryId=FixedCategories.FYV.id),
    Tomates(productName="Tomates", categoryId=FixedCategories.FYV.id),
    Lechuga(productName="Lechuga", categoryId=FixedCategories.FYV.id),
    Zanahorias(productName="Zanahorias", categoryId=FixedCategories.FYV.id),
    Espinacas(productName="Espinacas", categoryId=FixedCategories.FYV.id),
    Pimientos(productName="Pimientos", categoryId=FixedCategories.FYV.id),
    Cebollas(productName="Cebollas", categoryId=FixedCategories.FYV.id),
    Ajos(productName="Ajos", categoryId=FixedCategories.FYV.id),
    Pepinos(productName="Pepinos", categoryId=FixedCategories.FYV.id),
    Calabacines(productName="Calabacines", categoryId=FixedCategories.FYV.id),
    Berenjenas(productName="Berenjenas", categoryId=FixedCategories.FYV.id),
    Patatas(productName="Patatas", categoryId=FixedCategories.FYV.id),
    Limones(productName="Limones", categoryId=FixedCategories.FYV.id),
    Brocoli(productName="Brócoli", categoryId=FixedCategories.FYV.id),
    Coliflor(productName="Coliflor", categoryId=FixedCategories.FYV.id),
    Aguacates(productName="Aguacates", categoryId=FixedCategories.FYV.id),
    Setas(productName="Setas", categoryId=FixedCategories.FYV.id),

    //Carnes
    Pollo(productName="Pollo", categoryId=FixedCategories.CARNES.id),
    Ternera(productName="Ternera", categoryId=FixedCategories.CARNES.id),
    Cerdo(productName="Cerdo", categoryId=FixedCategories.CARNES.id),
    Cordero(productName="Cordero", categoryId=FixedCategories.CARNES.id),
    Pavo(productName="Pavo", categoryId=FixedCategories.CARNES.id),
    ChuletasDeCerdo(productName="Chuletas de cerdo", categoryId=FixedCategories.CARNES.id),
    FiletesDeTernera(productName="Filetes de ternera", categoryId=FixedCategories.CARNES.id),
    AlitasDePollo(productName="Alitas de pollo", categoryId=FixedCategories.CARNES.id),
    CarnePicada(productName="Carne picada", categoryId=FixedCategories.CARNES.id),
    SolomilloDeCerdo(productName="Solomillo de cerdo", categoryId=FixedCategories.CARNES.id),
    CostillasDeTernera(productName="Costillas de ternera", categoryId=FixedCategories.CARNES.id),
    MuslosDePollo(productName="Muslos de pollo", categoryId=FixedCategories.CARNES.id),
    JamonSerrano(productName="Jamón serrano", categoryId=FixedCategories.CARNES.id),
    Salchichas(productName="Salchichas", categoryId=FixedCategories.CARNES.id),
    LomoDeCerdo(productName="Lomo de cerdo", categoryId=FixedCategories.CARNES.id),
    Chorizo(productName="Chorizo", categoryId=FixedCategories.CARNES.id),
    Bacon(productName="Bacon", categoryId=FixedCategories.CARNES.id),
    Morcilla(productName="Morcilla", categoryId=FixedCategories.CARNES.id),
    PechugaDePollo(productName="Pechuga de pollo", categoryId=FixedCategories.CARNES.id),
    JamonCocido(productName="Jamón cocido", categoryId=FixedCategories.CARNES.id),

    //Pescado-Marisco
    Salmon(productName="Salmón", categoryId=FixedCategories.PYM.id),
    Atun(productName="Atún", categoryId=FixedCategories.PYM.id),
    Merluza(productName="Merluza", categoryId=FixedCategories.PYM.id),
    Bacalao(productName="Bacalao", categoryId=FixedCategories.PYM.id),
    Sardinas(productName="Sardinas", categoryId=FixedCategories.PYM.id),
    Calamares(productName="Calamares", categoryId=FixedCategories.PYM.id),
    Mejillones(productName="Mejillones", categoryId=FixedCategories.PYM.id),
    Gambas(productName="Gambas", categoryId=FixedCategories.PYM.id),
    Langostinos(productName="Langostinos", categoryId=FixedCategories.PYM.id),
    Pulpo(productName="Pulpo", categoryId=FixedCategories.PYM.id),
    Anchoas(productName="Anchoas", categoryId=FixedCategories.PYM.id),
    Caballa(productName="Caballa", categoryId=FixedCategories.PYM.id),
    Lenguado(productName="Lenguado", categoryId=FixedCategories.PYM.id),
    Trucha(productName="Trucha", categoryId=FixedCategories.PYM.id),
    Bonito(productName="Bonito", categoryId=FixedCategories.PYM.id),
    Sepia(productName="Sepia", categoryId=FixedCategories.PYM.id),
    Almejas(productName="Almejas", categoryId=FixedCategories.PYM.id),
    Ostras(productName="Ostras", categoryId=FixedCategories.PYM.id),
    Rodaballo(productName="Rodaballo", categoryId=FixedCategories.PYM.id),
    Boquerones(productName="Boquerones", categoryId=FixedCategories.PYM.id),

    //Latas
    AtunEnlatado(productName="Atún enlatado", categoryId=FixedCategories.LATAS.id),
    SardinasEnlatadas(productName="Sardinas enlatadas", categoryId=FixedCategories.LATAS.id),
    MaizEnlatado(productName="Maíz enlatado", categoryId=FixedCategories.LATAS.id),
    TomateFrito(productName="Tomate frito", categoryId=FixedCategories.LATAS.id),
    GarbanzosEnlatados(productName="Garbanzos enlatados", categoryId=FixedCategories.LATAS.id),
    JudiasVerdesEnlatadas(productName="Judías verdes enlatadas", categoryId=FixedCategories.LATAS.id),
    GuisantesEnlatados(productName="Guisantes enlatados", categoryId=FixedCategories.LATAS.id),
    ChilesEnlatados(productName="Chiles enlatados", categoryId=FixedCategories.LATAS.id),
    SopaEnlatada(productName="Sopa enlatada", categoryId=FixedCategories.LATAS.id),
    AnchoasEnlatadas(productName="Anchoas enlatadas", categoryId=FixedCategories.LATAS.id),
    MelocotonEnAlmibar(productName="Melocotón en almíbar", categoryId=FixedCategories.LATAS.id),
    PinhaEnAlmibar(productName="Piña en almíbar", categoryId=FixedCategories.LATAS.id),
    ChampinhonesEnlatados(productName="Champiñones enlatados", categoryId=FixedCategories.LATAS.id),
    AceitunasEnlatadas(productName="Aceitunas enlatadas", categoryId=FixedCategories.LATAS.id),
    LecheCondensada(productName="Leche condensada", categoryId=FixedCategories.LATAS.id),
    PateEnlatado(productName="Paté enlatado", categoryId=FixedCategories.LATAS.id),
    FrijolesEnlatados(productName="Frijoles enlatados", categoryId=FixedCategories.LATAS.id),
    PimientosEnlatados(productName="Pimientos enlatados", categoryId=FixedCategories.LATAS.id),
    SalsasEnlatadas(productName="Salsas enlatadas", categoryId=FixedCategories.LATAS.id),
    EsparragosEnlatados(productName="Espárragos enlatados", categoryId=FixedCategories.LATAS.id),

    //Lácteos
    Leche(productName="Leche", categoryId=FixedCategories.LACTEOS.id),
    QuesoCheddar(productName="Queso cheddar", categoryId=FixedCategories.LACTEOS.id),
    QuesoMozzarella(productName="Queso mozzarella", categoryId=FixedCategories.LACTEOS.id),
    QuesoParmesano(productName="Queso parmesano", categoryId=FixedCategories.LACTEOS.id),
    YogurNatural(productName="Yogur natural", categoryId=FixedCategories.LACTEOS.id),
    YogurGriego(productName="Yogur griego", categoryId=FixedCategories.LACTEOS.id),
    Mantequilla(productName="Mantequilla", categoryId=FixedCategories.LACTEOS.id),
    Margarina(productName="Margarina", categoryId=FixedCategories.LACTEOS.id),
    NataParaCocinar(productName="Nata para cocinar", categoryId=FixedCategories.LACTEOS.id),
    NataMontada(productName="Nata montada", categoryId=FixedCategories.LACTEOS.id),
    QuesoDeCabra(productName="Queso de cabra", categoryId=FixedCategories.LACTEOS.id),
    QuesoAzul(productName="Queso azul", categoryId=FixedCategories.LACTEOS.id),
    QuesoFresco(productName="Queso fresco", categoryId=FixedCategories.LACTEOS.id),
    Requeson(productName="Requesón", categoryId=FixedCategories.LACTEOS.id),
    BatidosDeLeche(productName="Batidos de leche", categoryId=FixedCategories.LACTEOS.id),
    QuesoGouda(productName="Queso gouda", categoryId=FixedCategories.LACTEOS.id),
    QuesoBrie(productName="Queso brie", categoryId=FixedCategories.LACTEOS.id),
    QuesoCamembert(productName="Queso camembert", categoryId=FixedCategories.LACTEOS.id),
    Helado(productName="Helado", categoryId=FixedCategories.LACTEOS.id),
    Kefir(productName="Kefir", categoryId=FixedCategories.LACTEOS.id),

    //Panadería
    PanDeMolde(productName="Pan de molde", categoryId=FixedCategories.PANADERIA.id),
    PanIntegral(productName="Pan integral", categoryId=FixedCategories.PANADERIA.id),
    PanDeCenteno(productName="Pan de centeno", categoryId=FixedCategories.PANADERIA.id),
    Bagels(productName="Bagels", categoryId=FixedCategories.PANADERIA.id),
    Croissants(productName="Croissants", categoryId=FixedCategories.PANADERIA.id),
    BollosDeLeche(productName="Bollos de leche", categoryId=FixedCategories.PANADERIA.id),
    Rosquillas(productName="Rosquillas", categoryId=FixedCategories.PANADERIA.id),
    Magdalenas(productName="Magdalenas", categoryId=FixedCategories.PANADERIA.id),
    PanDePita(productName="Pan de pita", categoryId=FixedCategories.PANADERIA.id),
    TortillasDeHarina(productName="Tortillas de harina", categoryId=FixedCategories.PANADERIA.id),
    Baguettes(productName="Baguettes", categoryId=FixedCategories.PANADERIA.id),
    PanSinGluten(productName="Pan sin gluten", categoryId=FixedCategories.PANADERIA.id),
    PanDeAjo(productName="Pan de ajo", categoryId=FixedCategories.PANADERIA.id),
    PanDeHamburguesa(productName="Pan de hamburguesa", categoryId=FixedCategories.PANADERIA.id),
    PanDePerritoCaliente(productName="Pan de perrito caliente", categoryId=FixedCategories.PANADERIA.id),
    PanDeAvena(productName="Pan de avena", categoryId=FixedCategories.PANADERIA.id),
    PanDeMaiz(productName="Pan de maíz", categoryId=FixedCategories.PANADERIA.id),
    Galletas(productName="Galletas", categoryId=FixedCategories.PANADERIA.id),
    Muffins(productName="Muffins", categoryId=FixedCategories.PANADERIA.id),
    Donuts(productName="Donuts", categoryId=FixedCategories.PANADERIA.id),

    //Bebidas
    AguaMineral(productName="Agua mineral", categoryId=FixedCategories.BEBIDAS.id),
    AguaConGas(productName="Agua con gas", categoryId=FixedCategories.BEBIDAS.id),
    ZumoDeNaranja(productName="Zumo de naranja", categoryId=FixedCategories.BEBIDAS.id),
    ZumoDeManzana(productName="Zumo de manzana", categoryId=FixedCategories.BEBIDAS.id),
    RefrescoDeCola(productName="Refresco de cola", categoryId=FixedCategories.BEBIDAS.id),
    RefrescoDeLimon(productName="Refresco de limón", categoryId=FixedCategories.BEBIDAS.id),
    RefrescoDeNaranja(productName="Refresco de naranja", categoryId=FixedCategories.BEBIDAS.id),
    TeHelado(productName="Té helado", categoryId=FixedCategories.BEBIDAS.id),
    Cafe(productName="Café", categoryId=FixedCategories.BEBIDAS.id),
    Cerveza(productName="Cerveza", categoryId=FixedCategories.BEBIDAS.id),
    VinoTinto(productName="Vino tinto", categoryId=FixedCategories.BEBIDAS.id),
    VinoBlanco(productName="Vino blanco", categoryId=FixedCategories.BEBIDAS.id),
    Sidra(productName="Sidra", categoryId=FixedCategories.BEBIDAS.id),
    Whisky(productName="Whisky", categoryId=FixedCategories.BEBIDAS.id),
    Vodka(productName="Vodka", categoryId=FixedCategories.BEBIDAS.id),
    Ron(productName="Ron", categoryId=FixedCategories.BEBIDAS.id),
    Ginebra(productName="Ginebra", categoryId=FixedCategories.BEBIDAS.id),
    Batidos(productName="Batidos", categoryId=FixedCategories.BEBIDAS.id),
    Limonada(productName="Limonada", categoryId=FixedCategories.BEBIDAS.id),
    BebidaEnergetica(productName="Bebida energética", categoryId=FixedCategories.BEBIDAS.id),

    //Desayuno
    Cereales(productName="Cereales", categoryId=FixedCategories.DESAYUNO.id),
    Avena(productName="Avena", categoryId=FixedCategories.DESAYUNO.id),
    Granola(productName="Granola", categoryId=FixedCategories.DESAYUNO.id),
    MermeladaDeFresa(productName="Mermelada de fresa", categoryId=FixedCategories.DESAYUNO.id),
    MermeladaDeNaranja(productName="Mermelada de naranja", categoryId=FixedCategories.DESAYUNO.id),
    MantequillaDeCacahuete(productName="Mantequilla de cacahuete", categoryId=FixedCategories.DESAYUNO.id),
    Miel(productName="Miel", categoryId=FixedCategories.DESAYUNO.id),
    Nutella(productName="Nutella", categoryId=FixedCategories.DESAYUNO.id),
    PanTostado(productName="Pan tostado", categoryId=FixedCategories.DESAYUNO.id),
    GalletasDeDesayuno(productName="Galletas de desayuno", categoryId=FixedCategories.DESAYUNO.id),
    BarritasDeCereales(productName="Barritas de cereales", categoryId=FixedCategories.DESAYUNO.id),
    Bizcochos(productName="Bizcochos", categoryId=FixedCategories.DESAYUNO.id),
    Tostadas(productName="Tostadas", categoryId=FixedCategories.DESAYUNO.id),
    FrutasSecas(productName="Frutas secas", categoryId=FixedCategories.DESAYUNO.id),
    Te(productName="Té", categoryId=FixedCategories.DESAYUNO.id),
    CaféSoluble(productName="Café soluble", categoryId=FixedCategories.DESAYUNO.id),
    LecheConChocolate(productName="Leche con chocolate", categoryId=FixedCategories.DESAYUNO.id),
    Infusiones(productName="Infusiones", categoryId=FixedCategories.DESAYUNO.id),
    LecheEnPolvo(productName="Leche en polvo", categoryId=FixedCategories.DESAYUNO.id),
    BebidaDeSoja(productName="Bebida de soja", categoryId=FixedCategories.DESAYUNO.id),

    //Especias-Salsas
    PimientaNegra(productName="Pimienta negra", categoryId=FixedCategories.EYS.id),
    Sal(productName="Sal", categoryId=FixedCategories.EYS.id),
    AjoEnPolvo(productName="Ajo en polvo", categoryId=FixedCategories.EYS.id),
    CebollaEnPolvo(productName="Cebolla en polvo", categoryId=FixedCategories.EYS.id),
    Oregano(productName="Orégano", categoryId=FixedCategories.EYS.id),
    Albahaca(productName="Albahaca", categoryId=FixedCategories.EYS.id),
    Perejil(productName="Perejil", categoryId=FixedCategories.EYS.id),
    Comino(productName="Comino", categoryId=FixedCategories.EYS.id),
    Pimenton(productName="Pimentón", categoryId=FixedCategories.EYS.id),
    Curry(productName="Curry", categoryId=FixedCategories.EYS.id),
    SalsaDeTomate(productName="Salsa de tomate", categoryId=FixedCategories.EYS.id),
    SalsaBarbacoa(productName="Salsa barbacoa", categoryId=FixedCategories.EYS.id),
    Mayonesa(productName="Mayonesa", categoryId=FixedCategories.EYS.id),
    Mostaza(productName="Mostaza", categoryId=FixedCategories.EYS.id),
    Ketchup(productName="Kétchup", categoryId=FixedCategories.EYS.id),
    SalsaDeSoja(productName="Salsa de soja", categoryId=FixedCategories.EYS.id),
    SalsaPicante(productName="Salsa picante", categoryId=FixedCategories.EYS.id),
    VinagreBalsamico(productName="Vinagre balsámico", categoryId=FixedCategories.EYS.id),
    AceiteDeOliva(productName="Aceite de oliva", categoryId=FixedCategories.EYS.id),
    AceiteDeGirasol(productName="Aceite de girasol", categoryId=FixedCategories.EYS.id),

    //Congelados
    VerdurasMixtasCongeladas(productName="Verduras mixtas congeladas", categoryId=FixedCategories.CONGELADOS.id),
    PizzaCongelada(productName="Pizza congelada", categoryId=FixedCategories.CONGELADOS.id),
    PatatasFritasCongeladas(productName="Patatas fritas congeladas", categoryId=FixedCategories.CONGELADOS.id),
    HeladoDeVainilla(productName="Helado de vainilla", categoryId=FixedCategories.CONGELADOS.id),
    HeladoDeChocolate(productName="Helado de chocolate", categoryId=FixedCategories.CONGELADOS.id),
    NuggetsDePolloCongelados(productName="Nuggets de pollo congelados", categoryId=FixedCategories.CONGELADOS.id),
    GambasCongeladas(productName="Gambas congeladas", categoryId=FixedCategories.CONGELADOS.id),
    PescadoEmpanadoCongelado(productName="Pescado empanado congelado", categoryId=FixedCategories.CONGELADOS.id),
    LasagnaCongelada(productName="Lasagna congelada", categoryId=FixedCategories.CONGELADOS.id),
    EmpanadillasCongeladas(productName="Empanadillas congeladas", categoryId=FixedCategories.CONGELADOS.id),
    FrutasCongeladas(productName="Frutas congeladas", categoryId=FixedCategories.CONGELADOS.id),
    ArandanosCongelados(productName="Arándanos congelados", categoryId=FixedCategories.CONGELADOS.id),
    FresasCongeladas(productName="Fresas congeladas", categoryId=FixedCategories.CONGELADOS.id),
    CroquetasCongeladas(productName="Croquetas congeladas", categoryId=FixedCategories.CONGELADOS.id),
    PanCongelado(productName="Pan congelado", categoryId=FixedCategories.CONGELADOS.id),
    HamburguesasVegetalesCongeladas(productName="Hamburguesas vegetales congeladas", categoryId=FixedCategories.CONGELADOS.id),
    PalitosDePescadoCongelados(productName="Palitos de pescado congelados", categoryId=FixedCategories.CONGELADOS.id),
    EspinacasCongeladas(productName="Espinacas congeladas", categoryId=FixedCategories.CONGELADOS.id),
    SorbeteDeLimon(productName="Sorbete de limón", categoryId=FixedCategories.CONGELADOS.id),
    TartasHeladas(productName="Tartas heladas", categoryId=FixedCategories.CONGELADOS.id),

    //Pasta
    Espaguetis(productName="Espaguetis", categoryId=FixedCategories.PASTA.id),
    Macarrones(productName="Macarrones", categoryId=FixedCategories.PASTA.id),
    Fideos(productName="Fideos", categoryId=FixedCategories.PASTA.id),
    Lasanha(productName="Lasaña", categoryId=FixedCategories.PASTA.id),
    Tallarines(productName="Tallarines", categoryId=FixedCategories.PASTA.id),
    Raviolis(productName="Raviolis", categoryId=FixedCategories.PASTA.id),
    Tortellinis(productName="Tortellinis", categoryId=FixedCategories.PASTA.id),
    Canelones(productName="Canelones", categoryId=FixedCategories.PASTA.id),
    Pappardelle(productName="Pappardelle", categoryId=FixedCategories.PASTA.id),
    Penne(productName="Penne", categoryId=FixedCategories.PASTA.id),
    Fusilli(productName="Fusilli", categoryId=FixedCategories.PASTA.id),
    Farfalle(productName="Farfalle", categoryId=FixedCategories.PASTA.id),
    Gnocchi(productName="Gnocchi", categoryId=FixedCategories.PASTA.id),
    Tagliatelle(productName="Tagliatelle", categoryId=FixedCategories.PASTA.id),
    Vermicelli(productName="Vermicelli", categoryId=FixedCategories.PASTA.id),
    Capellini(productName="Capellini", categoryId=FixedCategories.PASTA.id),
    Orzo(productName="Orzo", categoryId=FixedCategories.PASTA.id),
    Rigatoni(productName="Rigatoni", categoryId=FixedCategories.PASTA.id),
    Bucatini(productName="Bucatini", categoryId=FixedCategories.PASTA.id),
    Ziti(productName="Ziti", categoryId=FixedCategories.PASTA.id),

    //Snacks-Dulces
    PatatasFritas(productName="Patatas fritas", categoryId=FixedCategories.SNACKS.id),
    PalomitasDeMaiz(productName="Palomitas de maíz", categoryId=FixedCategories.SNACKS.id),
    GalletasDeChocolate(productName="Galletas de chocolate", categoryId=FixedCategories.SNACKS.id),
    BarritasDeGranola(productName="Barritas de granola", categoryId=FixedCategories.SNACKS.id),
    Pretzels(productName="Pretzels", categoryId=FixedCategories.SNACKS.id),
    FrutosSecosMixtos(productName="Frutos secos mixtos", categoryId=FixedCategories.SNACKS.id),
    AlmendrasSaladas(productName="Almendras saladas", categoryId=FixedCategories.SNACKS.id),
    Nueces(productName="Nueces", categoryId=FixedCategories.SNACKS.id),
    Pistachos(productName="Pistachos", categoryId=FixedCategories.SNACKS.id),
    Pasas(productName="Pasas", categoryId=FixedCategories.SNACKS.id),
    Gominolas(productName="Gominolas", categoryId=FixedCategories.SNACKS.id),
    ChocolateNegro(productName="Chocolate negro", categoryId=FixedCategories.SNACKS.id),
    ChocolateConLeche(productName="Chocolate con leche", categoryId=FixedCategories.SNACKS.id),
    GalletasSaladas(productName="Galletas saladas", categoryId=FixedCategories.SNACKS.id),
    Chicles(productName="Chicles", categoryId=FixedCategories.SNACKS.id),
    Caramelos(productName="Caramelos", categoryId=FixedCategories.SNACKS.id),
    Turron(productName="Turrón", categoryId=FixedCategories.SNACKS.id),
    Bombones(productName="Bombones", categoryId=FixedCategories.SNACKS.id),
    Churros(productName="Churros", categoryId=FixedCategories.SNACKS.id),
    DonasGlaseadas(productName="Donas glaseadas", categoryId=FixedCategories.SNACKS.id),

    //Limpieza
    DetergenteLiquido(productName="Detergente líquido", categoryId=FixedCategories.LIMPIEZA.id),
    JabonEnPolvo(productName="Jabón en polvo", categoryId=FixedCategories.LIMPIEZA.id),
    SuavizanteDeRopa(productName="Suavizante de ropa", categoryId=FixedCategories.LIMPIEZA.id),
    LimpiadorMultiusos(productName="Limpiador multiusos", categoryId=FixedCategories.LIMPIEZA.id),
    Desinfectante(productName="Desinfectante", categoryId=FixedCategories.LIMPIEZA.id),
    Lejia(productName="Lejía", categoryId=FixedCategories.LIMPIEZA.id),
    Limpiacristales(productName="Limpiacristales", categoryId=FixedCategories.LIMPIEZA.id),
    LimpiadorDeBanhos(productName="Limpiador de baños", categoryId=FixedCategories.LIMPIEZA.id),
    Desengrasante(productName="Desengrasante", categoryId=FixedCategories.LIMPIEZA.id),
    LimpiadorDeSuelos(productName="Limpiador de suelos", categoryId=FixedCategories.LIMPIEZA.id),
    Esponjas(productName="Esponjas", categoryId=FixedCategories.LIMPIEZA.id),
    Estropajos(productName="Estropajos", categoryId=FixedCategories.LIMPIEZA.id),
    PanhosDeLimpieza(productName="Paños de limpieza", categoryId=FixedCategories.LIMPIEZA.id),
    PapelDeCocina(productName="Papel de cocina", categoryId=FixedCategories.LIMPIEZA.id),
    BolsasDeBasura(productName="Bolsas de basura", categoryId=FixedCategories.LIMPIEZA.id),
    Fregasuelos(productName="Fregasuelos", categoryId=FixedCategories.LIMPIEZA.id),
    Quitamanchas(productName="Quitamanchas", categoryId=FixedCategories.LIMPIEZA.id),
    Ambientadores(productName="Ambientadores", categoryId=FixedCategories.LIMPIEZA.id),
    PastillasParaLavavajillas(productName="Pastillas para lavavajillas", categoryId=FixedCategories.LIMPIEZA.id),
    LimpiadorDeHornos(productName="Limpiador de hornos", categoryId=FixedCategories.LIMPIEZA.id),





}